### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by annepark** [annepark/rsfmri#1]
- [ ] add option to use custom ROIs (e.g., spherical) instead of FreeSurfer parcellations
- [ ] add nonparametric inference (PALM or randomise)
- [ ] allow users to specify multiple analyses (loop through designs)
- [ ] find a more precise way of generating GLM from user-defined files (csv? json?)
- [ ] make sure datasink includes any outputs that would be useful for QA
- [ ] convert jupyter notebook to python script, add argument parser
